Michi/popup massage
yutaroyoshikawa/grady pull request #124
Opened 2019-11-05 05:34 UTC by Micchili

完成してないです

コンポーネントの確認->dummy.vue
toastMassage->toastMasage.vue

2019-11-13 03:59 UTC, Micchili reviewed
無理やり筋肉で実装した所にコメントをつけたので、助言をください……

2019-11-13 03:59 UTC, Micchili commented on layouts/base.vue
> +    }
ここ、自分でみても大変汚い実装なので、何か良い処理方法があれば教えてください

2019-12-04 08:29 UTC, Micchili commented
ゆうたろうに教えてもらった所を直しました。
vuexのsubscribeActionを使い、moviesとsecretのメール送信を感知し
メールが送信される処理が発火した時にtoastMassageを出すようにしました。
setTimeoutで秒数を指定して、3秒たったら閉じるようにしています。

レビューお願いします！

2019-12-10 05:57 UTC, yutaroyoshikawa requested changes

2019-12-10 05:57 UTC, yutaroyoshikawa commented on layouts/movieThumbnail.vue
> +    height: 26vw;
min-widthとmin-heightをつけて欲しい🙏

2019-12-10 05:57 UTC, yutaroyoshikawa commented on pages/dammy.vue
> +      }
```
this.isOpen = !this.isOpen
```
の方が簡潔

2019-12-10 05:57 UTC, yutaroyoshikawa commented on store/base.ts
> +  }
showToastMessageは「トーストメッセージを見せる」という意味なのに、トーストメッセージをcloseする処理が入っているのはキモみが深い

2019-12-11 07:37 UTC, Micchili commented
@yutaroyoshikawa 
言われたとこ直したで！　レビューよろしくおねがいします！

showToastMessage                    -> openAndCloseToastMassage
min-widthとmin-heightをつけて欲しい -> max-widthとmax-heightを追加、minはissueに立ってるので、他のPRの所を直したらやります

2019-12-15 08:13 UTC, yutaroyoshikawa approved these changes
LGTM

2019-12-15 08:13 UTC, merged