Michishita/loading animation
yutaroyoshikawa/grady pull request #139
Opened 2019-12-05 06:38 UTC by Micchili

アニメーション処理を追加しました。

LodingMarkというコンポーネントを作り、base.vueに追加し、reservationsの値を監視して、Loadingの時のみマウントされるように処理を書きました。

gitignoreにnodeのバーションファイルを追加しました。

2019-12-09 01:44 UTC, yutaroyoshikawa requested changes

2019-12-09 01:44 UTC, yutaroyoshikawa commented on components/marks/loadingMark.vue
> +@keyframes loding {
loding
↓
# loading

2019-12-09 01:44 UTC, yutaroyoshikawa commented on pages/dammy.vue
>  </script>
dammy.vueはもう消しちゃっていいよ

2019-12-09 01:44 UTC, yutaroyoshikawa commented on layouts/base.vue
> +      </div>
baseレイアウトを採用してるページによっては今回のローディングアニメーション合わないところあるかも
ちょっとスタイル工夫必要かも

2019-12-17 04:24 UTC, Micchili commented
このローディングアニメーション、三つのStoreの
loadStateを監視しなきゃいけないので、base.tsにloadingAnimation.vueをマウントするか否かを判別するStoreを作った。

`const state = (): IState => ({
  isLoading = false
})

const mutations = {
  openLoading(state: IState) = {
   state.isLoading = true
},
 closeLoading(state: IState) = {
  state.isLoading = false
}
}
`

base.vueで各種storeのmutationを監視するためmethodsを作って、ifで判別する

`openAndCloseLoadingAnimation: function() {
  this.$store.subscribe(mutation => {
    if(mutation.type === 'movies/setMovieInfo') {
      while (this.$store.state.movies.loadState === !'none') {
        if(this.$store.state.movies.loadState === ' loading' && 'none') {
          this.$store.dispatch('base/openLoadingAnimation')
        }
        this.$store.dispatch('base/closeLoadingAnimation')
        blake
      }
    }
  }
}`

こういうのを作ったんだけど、これが動かない。
storeからisLoadingの値を取り出すとundefoundsになってる。
mutationが動いて、その次の処理には行くんだけどwhileの部分がおかしいのかマウントとアンマウントを800回くらい繰り返してそのまま死ぬ(動作が固まる)

これ、どうしてこんな処理にしたかというと、初めはtoastMassageとほぼ同じ感じで作ってて、subscribeActionでactionを監視してifでなんのActionかを判別してdispatchしてたんだけど、toastMassageはtimeOutで勝手にcloseしてくれるんだけど、 Loadingはそうではないので、toastMassageの処理だとcloseの処理が出来なくて、ifの処理が終わったらmethodがそのまま機能を停止するのでwhileに変えてみた。

今書いてる時に思いついたんだけど
methodをもう一つ生やして、open専用とclose専用の二つを作れば解決しそう。

2019-12-18 01:02 UTC, yutaroyoshikawa approved these changes
LGTM

2019-12-18 01:02 UTC, merged